# Generated by Django 4.2.2 on 2023-06-16 19:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vacationstationapi', '0002_vacationuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacation',
            name='user',
        ),
        migrations.AddField(
            model_name='vacation',
            name='vacation_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
