# Generated by Django 4.2.2 on 2023-06-20 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vacationstationapi', '0004_alter_vacation_vacation_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uservacation',
            name='user',
        ),
        migrations.AddField(
            model_name='uservacation',
            name='vacation_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vacationstationapi.vacationuser'),
        ),
    ]
